"""create livestock table

Revision ID: 04c2a2683abf
Revises: a92ff8213cfc
Create Date: 2026-08-20 11:35:02.988928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c2a2683abf'
down_revision: Union[str, Sequence[str], None] = 'a92ff8213cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livestock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_number', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'DECEASED', 'TRANSFERRED', name='livestockstatus'), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('dam_id', sa.UUID(), nullable=True),
    sa.Column('sire_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dam_id'], ['livestock.id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['livestock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livestock_tag_number'), 'livestock', ['tag_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_livestock_tag_number'), table_name='livestock')
    op.drop_table('livestock')
    # ### end Alembic commands ###
