"""create treatments table

Revision ID: 4afb9d64d135
Revises: 04c2a2683abf
Create Date: 2026-08-20 11:36:57.549275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afb9d64d135'
down_revision: Union[str, Sequence[str], None] = '04c2a2683abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('livestock_id', sa.UUID(), nullable=False),
    sa.Column('medicine_item_id', sa.UUID(), nullable=True),
    sa.Column('treatment_type', sa.Enum('DEWORMING', 'VACCINATION', 'ANTIBIOTIC', 'OTHER', name='treatmenttype'), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('dosage_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dosage_unit', sa.String(), nullable=True),
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('veterinarian', sa.String(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.ForeignKeyConstraint(['medicine_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatments')
    # ### end Alembic commands ###
