"""add fields, crops, crop_activities, harvests; PRODUCTION type; nullable sale customer_id

Revision ID: 8498729ad422
Revises: c05fc2478ae7
Create Date: 2026-09-01 01:51:17.683235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8498729ad422'
down_revision: Union[str, Sequence[str], None] = 'c05fc2478ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('size_unit', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('variety', sa.String(), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('quantity_planted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planting_unit', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'PLANTED', 'GROWING', 'HARVESTING', 'COMPLETED', 'FAILED', name='cropstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('LAND_PREPARATION', 'PLANTING', 'FERTILIZATION', 'SPRAYING', 'IRRIGATION', 'WEEDING', 'OTHER', name='cropactivitytype'), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('input_item_id', sa.UUID(), nullable=True),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['input_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('produce_inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['produce_inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harvests')
    op.drop_table('crop_activities')
    op.drop_table('crops')
    op.drop_table('fields')
    # ### end Alembic commands ###
