"""add farm_id to livestock/expense/equipment, add user_farm_access table

Revision ID: c05fc2478ae7
Revises: 31c54f8237db
Create Date: 2026-08-22 11:21:57.049631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05fc2478ae7'
down_revision: Union[str, Sequence[str], None] = '31c54f8237db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_farm_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'farm_id', name='uq_user_farm')
    )
    op.add_column('equipment', sa.Column('farm_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'equipment', 'farms', ['farm_id'], ['id'])
    op.add_column('expenses', sa.Column('farm_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'expenses', 'farms', ['farm_id'], ['id'])
    op.add_column('livestock', sa.Column('farm_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'livestock', 'farms', ['farm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'livestock', type_='foreignkey')
    op.drop_column('livestock', 'farm_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'farm_id')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'farm_id')
    op.drop_table('user_farm_access')
    # ### end Alembic commands ###
