/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Farms */
        get: operations["list_farms_api_v1_farms_get"];
        put?: never;
        /** Create Farm */
        post: operations["create_farm_api_v1_farms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stores */
        get: operations["list_stores_api_v1_stores_get"];
        put?: never;
        /** Create Store */
        post: operations["create_store_api_v1_stores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_inventory_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_inventory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/low-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Low Stock */
        get: operations["low_stock_api_v1_inventory_low_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_inventory__item_id__patch"];
        trace?: never;
    };
    "/api/v1/inventory/{item_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Transaction */
        post: operations["record_transaction_api_v1_inventory__item_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppliers */
        get: operations["list_suppliers_api_v1_suppliers_get"];
        put?: never;
        /** Create Supplier */
        post: operations["create_supplier_api_v1_suppliers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Supplier */
        patch: operations["update_supplier_api_v1_suppliers__supplier_id__patch"];
        trace?: never;
    };
    "/api/v1/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Purchases */
        get: operations["list_purchases_api_v1_purchases_get"];
        put?: never;
        /** Create Purchase */
        post: operations["create_purchase_api_v1_purchases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purchases/{purchase_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Purchase */
        get: operations["get_purchase_api_v1_purchases__purchase_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/livestock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Livestock */
        get: operations["list_livestock_api_v1_livestock_get"];
        put?: never;
        /** Create Livestock */
        post: operations["create_livestock_api_v1_livestock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/livestock/{livestock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Livestock */
        patch: operations["update_livestock_api_v1_livestock__livestock_id__patch"];
        trace?: never;
    };
    "/api/v1/veterinary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Treatment */
        post: operations["record_treatment_api_v1_veterinary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/veterinary/by-livestock/{livestock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Treatment History */
        get: operations["treatment_history_api_v1_veterinary_by_livestock__livestock_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/veterinary/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming Follow Ups */
        get: operations["upcoming_follow_ups_api_v1_veterinary_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_v1_customers_get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_api_v1_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sales */
        get: operations["list_sales_api_v1_sales_get"];
        put?: never;
        /** Create Sale */
        post: operations["create_sale_api_v1_sales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Expenses */
        get: operations["list_expenses_api_v1_expenses_get"];
        put?: never;
        /** Create Expense */
        post: operations["create_expense_api_v1_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expense Summary */
        get: operations["expense_summary_api_v1_expenses_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Equipment */
        get: operations["list_equipment_api_v1_equipment_get"];
        put?: never;
        /** Create Equipment */
        post: operations["create_equipment_api_v1_equipment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/upcoming-service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming Service */
        get: operations["upcoming_service_api_v1_equipment_upcoming_service_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/{equipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Equipment */
        patch: operations["update_equipment_api_v1_equipment__equipment_id__patch"];
        trace?: never;
    };
    "/api/v1/equipment/{equipment_id}/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Maintenance History */
        get: operations["maintenance_history_api_v1_equipment__equipment_id__maintenance_get"];
        put?: never;
        /** Record Maintenance */
        post: operations["record_maintenance_api_v1_equipment__equipment_id__maintenance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** CustomerCreate */
        CustomerCreate: {
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Address */
            address?: string | null;
        };
        /** CustomerOut */
        CustomerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Email */
            email: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Total Livestock */
            total_livestock: number;
            /** Low Stock Count */
            low_stock_count: number;
            /** Upcoming Treatments Count */
            upcoming_treatments_count: number;
            /** Inventory Value */
            inventory_value: string;
        };
        /** EquipmentCreate */
        EquipmentCreate: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Purchase Price */
            purchase_price?: number | string | null;
            /** Condition */
            condition?: string | null;
            /** Location */
            location?: string | null;
        };
        /** EquipmentOut */
        EquipmentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Serial Number */
            serial_number: string | null;
            /** Purchase Date */
            purchase_date: string | null;
            /** Purchase Price */
            purchase_price: string | null;
            /** Condition */
            condition: string | null;
            /** Location */
            location: string | null;
            status: components["schemas"]["EquipmentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EquipmentStatus
         * @enum {string}
         */
        EquipmentStatus: "OPERATIONAL" | "UNDER_MAINTENANCE" | "OUT_OF_SERVICE" | "DISPOSED";
        /** EquipmentUpdate */
        EquipmentUpdate: {
            /** Condition */
            condition?: string | null;
            /** Location */
            location?: string | null;
            status?: components["schemas"]["EquipmentStatus"] | null;
        };
        /**
         * ExpenseCategory
         * @enum {string}
         */
        ExpenseCategory: "FEED" | "VET_SERVICES" | "MEDICINE" | "SEEDS" | "FERTILIZER" | "LABOR" | "TRANSPORT" | "EQUIPMENT" | "UTILITIES" | "REPAIRS" | "OTHER";
        /** ExpenseCreate */
        ExpenseCreate: {
            category: components["schemas"]["ExpenseCategory"];
            /** Amount */
            amount: number | string;
            /**
             * Expense Date
             * Format: date
             */
            expense_date: string;
            /** Supplier Id */
            supplier_id?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ExpenseOut */
        ExpenseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            category: components["schemas"]["ExpenseCategory"];
            /** Amount */
            amount: string;
            /**
             * Expense Date
             * Format: date
             */
            expense_date: string;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExpenseSummary */
        ExpenseSummary: {
            category: components["schemas"]["ExpenseCategory"];
            /** Total */
            total: string;
        };
        /** FarmCreate */
        FarmCreate: {
            /** Name */
            name: string;
            /** County */
            county?: string | null;
            /** Sub County */
            sub_county?: string | null;
            /** Location */
            location?: string | null;
            /** Size */
            size?: number | string | null;
        };
        /** FarmOut */
        FarmOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** County */
            county: string | null;
            /** Location */
            location: string | null;
            /** Size */
            size: string | null;
            status: components["schemas"]["FarmStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FarmStatus
         * @enum {string}
         */
        FarmStatus: "ACTIVE" | "INACTIVE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InventoryCategory
         * @enum {string}
         */
        InventoryCategory: "ANIMAL_FEED" | "SEEDS" | "FERTILIZERS" | "PESTICIDES" | "VETERINARY_MEDICINE" | "DEWORMERS" | "ANTIBIOTICS" | "VACCINES" | "FUEL" | "TOOLS" | "CONSUMABLES" | "OTHER";
        /** InventoryItemCreate */
        InventoryItemCreate: {
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Name */
            name: string;
            category: components["schemas"]["InventoryCategory"];
            /** Unit */
            unit: string;
            /**
             * Quantity On Hand
             * @default 0
             */
            quantity_on_hand: number | string;
            /**
             * Reorder Level
             * @default 0
             */
            reorder_level: number | string;
            /**
             * Purchase Price
             * @default 0
             */
            purchase_price: number | string;
            /** Selling Price */
            selling_price?: number | string | null;
            /** Batch Number */
            batch_number?: string | null;
            /** Expiry Date */
            expiry_date?: string | null;
        };
        /** InventoryItemOut */
        InventoryItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Name */
            name: string;
            category: components["schemas"]["InventoryCategory"];
            /** Unit */
            unit: string;
            /** Quantity On Hand */
            quantity_on_hand: string;
            /** Reorder Level */
            reorder_level: string;
            /** Purchase Price */
            purchase_price: string;
            /** Selling Price */
            selling_price: string | null;
            /** Expiry Date */
            expiry_date: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InventoryItemUpdate */
        InventoryItemUpdate: {
            /** Name */
            name?: string | null;
            /** Reorder Level */
            reorder_level?: number | string | null;
            /** Purchase Price */
            purchase_price?: number | string | null;
            /** Selling Price */
            selling_price?: number | string | null;
            /** Batch Number */
            batch_number?: string | null;
            /** Expiry Date */
            expiry_date?: string | null;
        };
        /** LivestockCreate */
        LivestockCreate: {
            /** Tag Number */
            tag_number: string;
            /**
             * Species
             * @default Cattle
             */
            species: string;
            /** Breed */
            breed?: string | null;
            sex: components["schemas"]["Sex"];
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Acquisition Date */
            acquisition_date?: string | null;
            /** Source */
            source?: string | null;
            /** Location */
            location?: string | null;
            /** Dam Id */
            dam_id?: string | null;
            /** Sire Id */
            sire_id?: string | null;
        };
        /** LivestockOut */
        LivestockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Tag Number */
            tag_number: string;
            /** Species */
            species: string;
            /** Breed */
            breed: string | null;
            sex: components["schemas"]["Sex"];
            /** Date Of Birth */
            date_of_birth: string | null;
            status: components["schemas"]["LivestockStatus"];
            /** Location */
            location: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LivestockStatus
         * @enum {string}
         */
        LivestockStatus: "ACTIVE" | "SOLD" | "DECEASED" | "TRANSFERRED";
        /** LivestockUpdate */
        LivestockUpdate: {
            /** Breed */
            breed?: string | null;
            /** Location */
            location?: string | null;
            status?: components["schemas"]["LivestockStatus"] | null;
        };
        /** MaintenanceRecordCreate */
        MaintenanceRecordCreate: {
            /**
             * Maintenance Date
             * Format: date
             */
            maintenance_date: string;
            /** Service Type */
            service_type?: string | null;
            /** Description */
            description?: string | null;
            /** Cost */
            cost?: number | string | null;
            /** Next Service Date */
            next_service_date?: string | null;
        };
        /** MaintenanceRecordOut */
        MaintenanceRecordOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Equipment Id
             * Format: uuid
             */
            equipment_id: string;
            /**
             * Maintenance Date
             * Format: date
             */
            maintenance_date: string;
            /** Service Type */
            service_type: string | null;
            /** Description */
            description: string | null;
            /** Cost */
            cost: string | null;
            /** Next Service Date */
            next_service_date: string | null;
        };
        /**
         * PaymentStatus
         * @enum {string}
         */
        PaymentStatus: "PAID" | "PARTIAL" | "UNPAID";
        /** PurchaseCreate */
        PurchaseCreate: {
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Invoice Number */
            invoice_number?: string | null;
            /**
             * Purchase Date
             * Format: date
             */
            purchase_date: string;
            /** @default UNPAID */
            payment_status: components["schemas"]["PaymentStatus"];
            /** Items */
            items: components["schemas"]["PurchaseItemCreate"][];
        };
        /** PurchaseItemCreate */
        PurchaseItemCreate: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Quantity */
            quantity: number | string;
            /** Unit Price */
            unit_price: number | string;
        };
        /** PurchaseItemOut */
        PurchaseItemOut: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string;
        };
        /** PurchaseOut */
        PurchaseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Invoice Number */
            invoice_number: string | null;
            /**
             * Purchase Date
             * Format: date
             */
            purchase_date: string;
            payment_status: components["schemas"]["PaymentStatus"];
            /** Total Amount */
            total_amount: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Items */
            items: components["schemas"]["PurchaseItemOut"][];
        };
        /** SaleCreate */
        SaleCreate: {
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /**
             * Sale Date
             * Format: date
             */
            sale_date: string;
            /** @default UNPAID */
            payment_status: components["schemas"]["PaymentStatus"];
            /** Payment Method */
            payment_method?: string | null;
            /** Items */
            items: components["schemas"]["SaleItemCreate"][];
        };
        /** SaleItemCreate */
        SaleItemCreate: {
            item_type: components["schemas"]["SaleItemType"];
            /** Livestock Id */
            livestock_id?: string | null;
            /** Inventory Item Id */
            inventory_item_id?: string | null;
            /**
             * Quantity
             * @default 1
             */
            quantity: number | string;
            /** Unit Price */
            unit_price: number | string;
        };
        /** SaleItemOut */
        SaleItemOut: {
            item_type: components["schemas"]["SaleItemType"];
            /** Livestock Id */
            livestock_id: string | null;
            /** Inventory Item Id */
            inventory_item_id: string | null;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string;
        };
        /**
         * SaleItemType
         * @enum {string}
         */
        SaleItemType: "LIVESTOCK" | "PRODUCT";
        /** SaleOut */
        SaleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /**
             * Sale Date
             * Format: date
             */
            sale_date: string;
            payment_status: components["schemas"]["PaymentStatus"];
            /** Total Amount */
            total_amount: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Items */
            items: components["schemas"]["SaleItemOut"][];
        };
        /**
         * Sex
         * @enum {string}
         */
        Sex: "MALE" | "FEMALE";
        /** StockTransactionCreate */
        StockTransactionCreate: {
            /** Quantity */
            quantity: number | string;
            transaction_type: components["schemas"]["StockTransactionType"];
            /** Reference Type */
            reference_type?: string | null;
            /** Reference Id */
            reference_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * StockTransactionType
         * @enum {string}
         */
        StockTransactionType: "OPENING_BALANCE" | "PURCHASE" | "CONSUMPTION" | "SALE" | "TRANSFER" | "ADJUSTMENT" | "DAMAGE" | "EXPIRY" | "RETURN";
        /** StoreCreate */
        StoreCreate: {
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Name */
            name: string;
            /** Location */
            location?: string | null;
        };
        /** StoreOut */
        StoreOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Name */
            name: string;
            /** Location */
            location: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SupplierCreate */
        SupplierCreate: {
            /** Name */
            name: string;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Contact Email */
            contact_email?: string | null;
            /** Address */
            address?: string | null;
        };
        /** SupplierOut */
        SupplierOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Contact Phone */
            contact_phone: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Address */
            address: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SupplierUpdate */
        SupplierUpdate: {
            /** Name */
            name?: string | null;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Contact Email */
            contact_email?: string | null;
            /** Address */
            address?: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TreatmentCreate */
        TreatmentCreate: {
            /**
             * Livestock Id
             * Format: uuid
             */
            livestock_id: string;
            /** Medicine Item Id */
            medicine_item_id?: string | null;
            treatment_type: components["schemas"]["TreatmentType"];
            /** Diagnosis */
            diagnosis?: string | null;
            /** Dosage Quantity */
            dosage_quantity?: number | string | null;
            /** Dosage Unit */
            dosage_unit?: string | null;
            /**
             * Treatment Date
             * Format: date
             */
            treatment_date: string;
            /** Follow Up Date */
            follow_up_date?: string | null;
            /** Veterinarian */
            veterinarian?: string | null;
            /** Cost */
            cost?: number | string | null;
            /** Notes */
            notes?: string | null;
        };
        /** TreatmentOut */
        TreatmentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Livestock Id
             * Format: uuid
             */
            livestock_id: string;
            /** Medicine Item Id */
            medicine_item_id: string | null;
            treatment_type: components["schemas"]["TreatmentType"];
            /** Diagnosis */
            diagnosis: string | null;
            /**
             * Treatment Date
             * Format: date
             */
            treatment_date: string;
            /** Follow Up Date */
            follow_up_date: string | null;
            /** Veterinarian */
            veterinarian: string | null;
            /** Cost */
            cost: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TreatmentType
         * @enum {string}
         */
        TreatmentType: "DEWORMING" | "VACCINATION" | "ANTIBIOTIC" | "OTHER";
        /** UserCreate */
        UserCreate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** @default GENERAL_STAFF */
            role: components["schemas"]["UserRole"];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "ADMIN" | "FARM_MANAGER" | "INVENTORY_STAFF" | "VETERINARY_STAFF" | "SALES_STAFF" | "GENERAL_STAFF";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_farms_api_v1_farms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmOut"][];
                };
            };
        };
    };
    create_farm_api_v1_farms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stores_api_v1_stores_get: {
        parameters: {
            query?: {
                farm_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_store_api_v1_stores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_inventory_get: {
        parameters: {
            query?: {
                store_id?: string | null;
                search?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_inventory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    low_stock_api_v1_inventory_low_stock_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemOut"][];
                };
            };
        };
    };
    update_item_api_v1_inventory__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_transaction_api_v1_inventory__item_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockTransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suppliers_api_v1_suppliers_get: {
        parameters: {
            query?: {
                search?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplier_api_v1_suppliers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_supplier_api_v1_suppliers__supplier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_purchases_api_v1_purchases_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_purchase_api_v1_purchases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_purchase_api_v1_purchases__purchase_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_livestock_api_v1_livestock_get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivestockOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_livestock_api_v1_livestock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LivestockCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivestockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_livestock_api_v1_livestock__livestock_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                livestock_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LivestockUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivestockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_treatment_api_v1_veterinary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TreatmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreatmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    treatment_history_api_v1_veterinary_by_livestock__livestock_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                livestock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreatmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upcoming_follow_ups_api_v1_veterinary_upcoming_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreatmentOut"][];
                };
            };
        };
    };
    list_customers_api_v1_customers_get: {
        parameters: {
            query?: {
                search?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_api_v1_customers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sales_api_v1_sales_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sale_api_v1_sales_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expenses_api_v1_expenses_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_api_v1_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expense_summary_api_v1_expenses_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseSummary"][];
                };
            };
        };
    };
    get_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    list_equipment_api_v1_equipment_get: {
        parameters: {
            query?: {
                search?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_equipment_api_v1_equipment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upcoming_service_api_v1_equipment_upcoming_service_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceRecordOut"][];
                };
            };
        };
    };
    update_equipment_api_v1_equipment__equipment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maintenance_history_api_v1_equipment__equipment_id__maintenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceRecordOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_maintenance_api_v1_equipment__equipment_id__maintenance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceRecordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
